services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: govision-backend
    ports:
      - "8046:8046"
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - govision-db-network
      - govision-model-network

networks:
  govision-db-network:
    external: true
  govision-model-network:
    external: true
