services:
  database:
    image: postgres:14.3
    container_name: govision-db
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - govision-db-network

volumes:
  dbdata:
    driver: local

networks:
  govision-db-network:
    driver: bridge