version: '3.8'

services:
  database:
    image: postgres:14.3
    container_name: govision-db
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: govision-backend
    ports:
      - "8046:8046"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - database  # Ensure backend starts after the database service
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "database", "-p", "5432", "-U", "gv_admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    entrypoint: ["sh", "-c", "until pg_isready -h database -p 5432 -U gv_admin; do echo 'Waiting for DB'; sleep 2; done; ./main"]

volumes:
  dbdata:
    driver: local
