services:
  database:
    image: postgres:14.3
    container_name: govision-db
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
